spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  threads:
    virtual:
      enabled: true
